### ISSUE TITLE
thank you for putting this out there!

### ISSUE THREAD

**Issue by brianwu02** [PhantomInsights/subreddit-analyzer#3]
First of all, thank you for making this public :) Have always wanted to do something like this but have been lazy.

It would be great if you could put some simple instructions on how to install / use it without reading the source too much :P (like if I could see what you're running in cmd line)

Merry Christmas :)

**Comment by agentphantom** [comment]
Thank you for your comment!

Writting a step by step tutorial will take a bit of time, what I can tell you is that I use Visual Studio Code to run these scripts. This is because Visual Studio Code has a built in terminal where you can see the output of the scripts you run.

The easiest way to get started is to download all the files in this repository and unzipping them in any folder.

Then you will require to move all the .csv files from the data folder into the scripts folder, then open the scripts folder with Visual Studio Code and from there you can play with step3.py

In step3.py you will require to specify at the bottom of the file the function you want to test.

Also, if you want to download datasets from other subreddits you can edit any of the submissions/comments scripts and set up your own variables.

**Comment by brianwu02** [comment]
Ha, maybe I was going to get a tutorial for christmas =P

Code is structured and simple to read so doing that, thank you!
